// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: amazon-assistant-v1

#ifndef _AMAZON_ASSISTANT_V1_UI_H
#define _AMAZON_ASSISTANT_V1_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Image2;
void ui_event_Image1(lv_event_t * e);
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
void ui_event_Image5(lv_event_t * e);
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Image6;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Button7;
void ui_event_Image7(lv_event_t * e);
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Button10;
void ui_event_Label13(lv_event_t * e);
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_TabView2;
extern lv_obj_t * ui_Pending;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Unshipped;
extern lv_obj_t * ui_Canceled;
extern lv_obj_t * ui_Shipped;
extern lv_obj_t * ui_Button12;
extern lv_obj_t * ui_Label36;
extern lv_obj_t * ui_Button13;
extern lv_obj_t * ui_Label37;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Image14;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Image16;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Label26;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
void ui_event_Label27(lv_event_t * e);
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_Label35;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_vector_png);    // assets/Vector.png
LV_IMG_DECLARE(ui_img_package_png);    // assets/package.png
LV_IMG_DECLARE(ui_img_view_orders_button_png);    // assets/view orders button.png
LV_IMG_DECLARE(ui_img_pa_rudolph_png);    // assets/pa_rudolph.png
LV_IMG_DECLARE(ui_img_messages_png);    // assets/messages.png
LV_IMG_DECLARE(ui_img_mug_png);    // assets/mug.png
LV_IMG_DECLARE(ui_img_825004913);    // assets/check-out 1.png
LV_IMG_DECLARE(ui_img_825004913);    // assets/check-out 1.png
LV_IMG_DECLARE(ui_img_image_1_png);    // assets/image 1.png



LV_FONT_DECLARE(ui_font_datefont);
LV_FONT_DECLARE(ui_font_locategoodsfont);
LV_FONT_DECLARE(ui_font_percentage_font_white);
LV_FONT_DECLARE(ui_font_revenuetodayfont);
LV_FONT_DECLARE(ui_font_revenue_order_number_font);
LV_FONT_DECLARE(ui_font_timefont);
LV_FONT_DECLARE(ui_font_welcomefont);
LV_FONT_DECLARE(ui_font_labelfont);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
